"""empty message

Revision ID: 177a8cb2238f
Revises: 33378e739948
Create Date: 2022-08-01 10:51:25.830855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177a8cb2238f'
down_revision = '33378e739948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selectors', 'specification_selector_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selectors', sa.Column('specification_selector_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
