"""empty message

Revision ID: 33378e739948
Revises: e04f8517e5a8
Create Date: 2022-07-29 14:42:24.135740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33378e739948'
down_revision = 'e04f8517e5a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selectors', sa.Column('brand_selector_id', sa.String(), nullable=True))
    op.add_column('selectors', sa.Column('specification_selector_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selectors', 'specification_selector_id')
    op.drop_column('selectors', 'brand_selector_id')
    # ### end Alembic commands ###
