"""empty message

Revision ID: 936bbb9594f2
Revises: 177a8cb2238f
Create Date: 2022-08-01 11:01:02.307558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936bbb9594f2'
down_revision = '177a8cb2238f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brands', sa.Column('brand_selector', sa.String(), nullable=True))
    op.add_column('brands', sa.Column('linking_url', sa.String(), nullable=True))
    op.drop_column('selectors', 'linking_url_selector')
    op.drop_column('selectors', 'brand_selector_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selectors', sa.Column('brand_selector_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('selectors', sa.Column('linking_url_selector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('brands', 'linking_url')
    op.drop_column('brands', 'brand_selector')
    # ### end Alembic commands ###
