"""empty message

Revision ID: b0a4acbf5a08
Revises: 936bbb9594f2
Create Date: 2022-08-02 11:45:41.822506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a4acbf5a08'
down_revision = '936bbb9594f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_website_url_id', table_name='website_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_website_url_id', 'website_url', ['id'], unique=False)
    # ### end Alembic commands ###
