"""empty message

Revision ID: e04f8517e5a8
Revises: 7d30ed2c35df
Create Date: 2022-07-28 15:11:23.759719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e04f8517e5a8'
down_revision = '7d30ed2c35df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('selectors', sa.Column('linking_url_selector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('selectors', 'linking_url_selector')
    # ### end Alembic commands ###
